apiVersion: v1
kind: Service
metadata:
  name: common-service
spec:
  selector:
    app: common-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  reverse-proxy-drop-useragent: |
    server {
      listen 80;
      server_name _;
      
      if ($http_user_agent = "") { return 403; }

      location / {
        proxy_pass http://localhost:8080/;
        proxy_set_header Host $http_host;
      }
    }
