---
apiVersion: v1
kind: Pod
metadata:
  name: common-pod
  labels:
    app: common-pod
spec:
  containers:
  - image: webratio/nodejs-http-server
    name: web-container
  - image: nginx:latest
    name: ambassador-container
    volumeMounts:
      - name: nginx
        mountPath: /etc/nginx/conf.d
    ports:
      - containerPort: 80
  volumes:
  - name: nginx
    configMap:
      name: nginx-config
      items:
        - key: reverse-proxy-drop-useragent
          path: default.conf