apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  clusterIP: None  # This makes it a headless service
  selector:
    app: mysql-db
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql