apiVersion: v1
kind: Pod
metadata:
  name: dev-hello-world-pod
  namespace: dev
spec:
  containers:
  - name: hello-world
    image: ghcr.io/hungtran84/hello-app:1.0
    ports:
    - containerPort: 80